"""add_isin_metadata_table

Revision ID: 149d8b3586f3
Revises: 358a6fb54030
Create Date: 2025-12-19 12:18:42.631756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149d8b3586f3'
down_revision: Union[str, Sequence[str], None] = '358a6fb54030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isin_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('STOCK', 'BOND', 'REAL_ASSET', name='isintype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin', name='uq_isin_metadata_isin')
    )
    op.create_index('idx_isin_metadata_isin', 'isin_metadata', ['isin'], unique=False)
    op.create_index('idx_isin_metadata_type', 'isin_metadata', ['type'], unique=False)
    op.create_index(op.f('ix_isin_metadata_isin'), 'isin_metadata', ['isin'], unique=True)
    op.create_index(op.f('ix_isin_metadata_type'), 'isin_metadata', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_isin_metadata_type'), table_name='isin_metadata')
    op.drop_index(op.f('ix_isin_metadata_isin'), table_name='isin_metadata')
    op.drop_index('idx_isin_metadata_type', table_name='isin_metadata')
    op.drop_index('idx_isin_metadata_isin', table_name='isin_metadata')
    op.drop_table('isin_metadata')
    # ### end Alembic commands ###
