"""add_position_values_table

Revision ID: 358a6fb54030
Revises: 3ff3f0eefe40
Create Date: 2025-12-18 18:31:39.597385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358a6fb54030'
down_revision: Union[str, Sequence[str], None] = '3ff3f0eefe40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin', name='uq_position_value_isin')
    )
    op.create_index('idx_position_value_isin', 'position_values', ['isin'], unique=False)
    op.create_index(op.f('ix_position_values_isin'), 'position_values', ['isin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_values_isin'), table_name='position_values')
    op.drop_index('idx_position_value_isin', table_name='position_values')
    op.drop_table('position_values')
    # ### end Alembic commands ###
