"""add_asset_snapshots_table

Revision ID: 3ebbf274293e
Revises: ba73f314112c
Create Date: 2025-12-21 12:44:02.747408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ebbf274293e'
down_revision: Union[str, Sequence[str], None] = 'ba73f314112c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_detail', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('value_eur', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_date', 'asset_snapshots', ['snapshot_date'], unique=False)
    op.create_index('idx_snapshot_date_asset_type', 'asset_snapshots', ['snapshot_date', 'asset_type'], unique=False)
    op.create_index(op.f('ix_asset_snapshots_asset_type'), 'asset_snapshots', ['asset_type'], unique=False)
    op.create_index(op.f('ix_asset_snapshots_snapshot_date'), 'asset_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_snapshots_snapshot_date'), table_name='asset_snapshots')
    op.drop_index(op.f('ix_asset_snapshots_asset_type'), table_name='asset_snapshots')
    op.drop_index('idx_snapshot_date_asset_type', table_name='asset_snapshots')
    op.drop_index('idx_snapshot_date', table_name='asset_snapshots')
    op.drop_table('asset_snapshots')
    # ### end Alembic commands ###
