"""initial_transaction_table

Revision ID: 3ff3f0eefe40
Revises: 
Create Date: 2025-12-16 23:36:22.745319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff3f0eefe40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('broker', sa.String(length=100), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('units', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='transactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('fee >= 0', name='check_non_negative_fee'),
    sa.CheckConstraint('price_per_unit > 0', name='check_positive_price'),
    sa.CheckConstraint('units > 0', name='check_positive_units'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_date_isin', 'transactions', ['date', 'isin'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_isin'), 'transactions', ['isin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_isin'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index('idx_date_isin', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
