"""add_other_assets_table

Revision ID: 62e0e9b2b3a9
Revises: 149d8b3586f3
Create Date: 2025-12-19 15:41:57.938781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e0e9b2b3a9'
down_revision: Union[str, Sequence[str], None] = '149d8b3586f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_detail', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type', 'asset_detail', name='uq_other_asset_type_detail')
    )
    op.create_index('idx_other_asset_type', 'other_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_other_assets_asset_type'), 'other_assets', ['asset_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_other_assets_asset_type'), table_name='other_assets')
    op.drop_index('idx_other_asset_type', table_name='other_assets')
    op.drop_table('other_assets')
    # ### end Alembic commands ###
