"""add_user_settings_table

Revision ID: ba73f314112c
Revises: 62e0e9b2b3a9
Create Date: 2025-12-21 10:23:53.014109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba73f314112c'
down_revision: Union[str, Sequence[str], None] = '62e0e9b2b3a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=50), nullable=False),
    sa.Column('setting_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key', name='uq_user_setting_key')
    )
    op.create_index('idx_user_setting_key', 'user_settings', ['setting_key'], unique=False)
    op.create_index(op.f('ix_user_settings_setting_key'), 'user_settings', ['setting_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_setting_key'), table_name='user_settings')
    op.drop_index('idx_user_setting_key', table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
